# Generated by Django 4.2.1 on 2023-05-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='products',
            name='desciption',
            field=models.TextField(null=True),
        ),
    ]
