# Generated by Django 4.2.1 on 2023-05-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_products_options_products_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='desciption',
            new_name='description',
        ),
    ]
